services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017" # $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123